import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const argIndex = process.argv.indexOf("--env");
const requested = process.env.ADMIN_HUB_ENV || (argIndex >= 0 ? process.argv[argIndex + 1] : "demo") || "demo";

if (!['demo', 'production'].includes(requested)) {
  console.error(`Refusing to build unknown Admin Hub environment: ${requested}`);
  process.exit(1);
}

const destination = resolve(root, "src/generated-environment.js");
await mkdir(dirname(destination), { recursive: true });
await writeFile(destination, `// Generated by scripts/build-env.js. Do not edit for deployment.\nexport const APP_ENV = ${JSON.stringify(requested)};\n`);
console.log(`Admin Hub build environment: ${requested}`);
