import { formatDate, formatDateRange } from "../../date-utils.js";
import { aggregateStudents, calculateAverageDuration, calculateTotalDuration, filterVisits, groupVisitsByDate, groupVisitsByIntervention, groupVisitsByReason, groupVisitsByRoom, summarize, sortNewest } from "./pace-analytics.js";
import { dateRangeControl } from "../../components/date-range.js";
import { emptyState, esc, formatMinutes, metricCard, pill } from "../../components/html.js";

function header(title, subtitle, range, section = "Overview") {
  return `<div class="page-header"><div><div class="eyebrow">PACE / ${esc(section)}</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${dateRangeControl(range)}</div>`;
}

function barList(title, rows, empty = "No data in this range.") {
  const max = Math.max(...rows.map(row => row.count), 1);
  return `<section class="panel chart-panel"><div class="panel-heading"><div><h2>${esc(title)}</h2><p>Completed visits in the selected range</p></div></div>${rows.length ? `<div class="bar-list">${rows.slice(0, 7).map(row => `<div class="bar-row"><div class="bar-label" title="${esc(row.label)}">${esc(row.label)}</div><div class="bar-track"><span style="width:${Math.max(4, row.count / max * 100)}%"></span></div><div class="bar-count">${row.count}</div></div>`).join("")}</div>` : emptyState("No activity yet", empty)}</section>`;
}

function trendChart(rows) {
  if (!rows.length) return emptyState("No visits in this range", "Daily activity will appear here when PACE visits are available.");
  const max = Math.max(...rows.map(row => row.count), 1);
  return `<div class="trend-chart" role="img" aria-label="Visits by date">${rows.map(row => `<div class="trend-column"><div class="trend-count">${row.count}</div><div class="trend-bar" style="height:${Math.max(8, row.count / max * 110)}px"></div><div class="trend-label">${esc(formatDate(row.label, { month: "short", day: "numeric" }))}</div></div>`).join("")}</div>`;
}

function detailModal(visit) {
  if (!visit) return "";
  const field = (label, value) => `<div class="detail-field"><dt>${esc(label)}</dt><dd>${value ? esc(value) : "<span class=\"muted\">Not recorded</span>"}</dd></div>`;
  return `<div class="modal-backdrop" data-close-modal><section class="modal" role="dialog" aria-modal="true" aria-labelledby="visit-detail-title"><button class="modal-close" data-close-modal aria-label="Close">×</button><div class="eyebrow">PACE visit detail</div><h2 id="visit-detail-title">${esc(visit.student || "Unnamed student")}</h2><p class="modal-subtitle">${esc(formatDate(visit.date))} · ${esc(visit.timeIn || "Time not recorded")}${visit.timeOut ? `–${esc(visit.timeOut)}` : ""}</p><dl class="detail-grid">${field("Duration", formatMinutes(visit.durationMinutes))}${field("Room", visit.room)}${field("Reason", visit.reasons.join(", "))}${field("Intervention / support", visit.interventions.join(", "))}${field("Behavior specialist", visit.specialists.join(", "))}${field("Teacher came from", visit.teacherCameFrom)}${field("SCM", visit.scmUsed === null ? "Not recorded" : visit.scmUsed ? "Yes" : "No")}${field("Notes", visit.notes)}</dl><p class="read-only-note">Read-only view. Corrections remain in PACE Room Tracker for now.</p></section></div>`;
}

export function renderHome() {
  return `<section class="home-page"><div class="home-hero"><div class="eyebrow">IU29 ADMINISTRATIVE SYSTEMS</div><h1>Admin Hub</h1><p>Operational intelligence for student support and administrative systems.</p></div><div class="section-heading"><div><h2>Modules</h2><p>Shared administrative views, built to grow one module at a time.</p></div></div><div class="module-grid"><a class="module-card active" href="#/pace"><div class="module-mark pace-mark">P</div><div><div class="module-title">PACE</div><p>View student visits, usage patterns, duration, interventions and activity.</p><span class="module-link">Open dashboard <span>→</span></span></div></a><div class="module-card disabled"><div class="module-mark muted-mark">D</div><div><div class="module-title">Discipline <span class="status-chip">Coming Soon</span></div><p>Referral and follow-up intelligence.</p></div></div><div class="module-card disabled"><div class="module-mark muted-mark">S</div><div><div class="module-title">Student Support <span class="status-chip">Coming Soon</span></div><p>Operational support tracking.</p></div></div></div><div class="home-note"><span class="note-icon">i</span><div><strong>Admin-facing and read-only</strong><p>Admin Hub helps administrators see, understand, filter and act on operational information. Data correction is intentionally left in the source workflow for V1.</p></div></div></section>`;
}

export function renderOverview(visits, range, activeVisit) {
  const summary = summarize(visits, range); const completed = summary.records.filter(row => row.isCompleted);
  const trend = groupVisitsByDate(completed).sort((a, b) => a.label.localeCompare(b.label));
  return `${header("PACE Overview", "A clear view of visits, supports and activity patterns.", range)}<div class="kpi-grid">${metricCard("PACE visits", summary.visits, formatDateRange(range))}${metricCard("Unique students seen", summary.uniqueStudents, "Students with a completed visit")}${metricCard("Average visit duration", formatMinutes(summary.averageDuration), "Completed visits with duration")}${metricCard("SCM events", summary.scmEvents === null ? "—" : summary.scmEvents, summary.scmEvents === null ? "Not recorded in this range" : "SCM marked Yes")}${range.preset === "today" ? metricCard("Currently in PACE", summary.currentlyInPace, "Open visits dated today") : ""}</div><div class="overview-grid"><section class="panel trend-panel"><div class="panel-heading"><div><h2>Visits over time</h2><p>How much PACE activity occurred on each day?</p></div><span class="panel-meta">${summary.visits} completed</span></div>${trendChart(trend)}</section>${barList("Reasons for visits", groupVisitsByReason(completed))}${barList("Interventions / supports", groupVisitsByIntervention(completed))}${barList("Visits by room", groupVisitsByRoom(completed))}</div>${activeVisit ? detailModal(activeVisit) : ""}`;
}

export function renderStudents(visits, range, state, activeVisit) {
  const rows = aggregateStudents(filterVisits(visits, range)).filter(row => row.student.toLowerCase().includes((state.studentsSearch ?? "").toLowerCase())).sort((a, b) => { const field = state.studentsSort ?? "visits"; return typeof a[field] === "string" ? a[field].localeCompare(b[field]) : (b[field] ?? 0) - (a[field] ?? 0); });
  const arrow = field => state.studentsSort === field ? " ↕" : "";
  return `${header("Students", "Compare PACE use by student for the selected range.", range, "Students")}<section class="panel"><div class="table-toolbar"><div><h2>Student activity</h2><p>${rows.length} student${rows.length === 1 ? "" : "s"} with completed visits</p></div><label class="search-field"><span>Search</span><input id="studentsSearch" type="search" placeholder="Search students" value="${esc(state.studentsSearch ?? "")}"></label></div>${rows.length ? `<div class="table-scroll"><table><thead><tr><th><button data-sort="student">Student${arrow("student")}</button></th><th><button data-sort="visits">Visits${arrow("visits")}</button></th><th><button data-sort="totalMinutes">Total PACE time${arrow("totalMinutes")}</button></th><th><button data-sort="averageDuration">Avg. duration${arrow("averageDuration")}</button></th><th><button data-sort="lastVisit">Last visit${arrow("lastVisit")}</button></th><th><button data-sort="scmEvents">SCM events${arrow("scmEvents")}</button></th></tr></thead><tbody>${rows.map(row => `<tr class="clickable-row" data-student="${esc(row.student)}"><td><a href="#/pace/students/${encodeURIComponent(row.student)}">${esc(row.student)}</a></td><td>${row.visits}</td><td>${formatMinutes(row.totalMinutes)}</td><td>${formatMinutes(row.averageDuration)}</td><td>${esc(formatDate(row.lastVisit))}</td><td>${row.scmEvents || "—"}</td></tr>`).join("")}</tbody></table></div>` : emptyState("No students found", "Try a different search or date range.")}</section>${activeVisit ? detailModal(activeVisit) : ""}`;
}

export function renderStudentDetail(visits, range, student, activeVisit) {
  const selected = filterVisits(visits, { ...range, student }); const summary = summarize(selected, range); const history = [...selected].sort(sortNewest); const reasons = groupVisitsByReason(selected); const interventions = groupVisitsByIntervention(selected);
  if (!student || !selected.length) return `${header("Student detail", "No PACE records matched this student and date range.", range, "Students")}<a class="back-link" href="#/pace/students">← Back to students</a>${emptyState("No matching visits", "Return to Students and choose another student.")}`;
  return `${header(student, `PACE-specific detail for ${formatDateRange(range)}.`, range, "Student detail")}<a class="back-link" href="#/pace/students">← Back to students</a><div class="kpi-grid compact">${metricCard("Visits", summary.visits)}${metricCard("Total PACE time", formatMinutes(calculateTotalDuration(selected)))}${metricCard("Average duration", formatMinutes(calculateAverageDuration(selected)))}${metricCard("Last visit", formatDate(history[0]?.date))}${metricCard("SCM events", summary.scmEvents === null ? "—" : summary.scmEvents)}</div><div class="detail-columns"><div>${barList("Reasons", reasons)}${barList("Interventions / supports", interventions)}</div><section class="panel"><div class="panel-heading"><div><h2>Visit history</h2><p>Chronological records for this student in the selected range.</p></div></div><div class="history-list">${history.map(visit => `<button class="history-item" data-visit="${esc(visit.id)}"><span class="history-date">${esc(formatDate(visit.date))}</span><span class="history-main"><strong>${esc(visit.timeIn || "Time not recorded")}${visit.timeOut ? `–${esc(visit.timeOut)}` : ""}</strong><span>${esc(visit.room || "Room not recorded")} · ${esc(visit.reasons.join(", ") || "Reason not recorded")}</span></span><span>${formatMinutes(visit.durationMinutes)}</span></button>`).join("")}</div></section></div>${activeVisit ? detailModal(activeVisit) : ""}`;
}

export function renderActivity(visits, range, state, activeVisit) {
  const all = filterVisits(visits, range); const filters = state.activityFilters ?? {};
  const rows = filterVisits(all, { ...filters, from: range.from, to: range.to });
  const unique = key => [...new Set(all.flatMap(v => key === "specialist" ? v.specialists : key === "reason" ? v.reasons : [v[key]]).filter(Boolean))].sort((a, b) => a.localeCompare(b));
  const select = (id, label, values) => `<label class="filter-field"><span>${esc(label)}</span><select data-activity-filter="${id}"><option value="">All</option>${values.map(value => `<option value="${esc(value)}" ${filters[id] === value ? "selected" : ""}>${esc(value)}</option>`).join("")}</select></label>`;
  return `${header("Activity Log", "Scan and filter PACE visits without changing source records.", range, "Activity Log")}<section class="panel"><div class="filter-grid"><label class="filter-field wide"><span>Search</span><input data-activity-filter="search" type="search" placeholder="Student, room, reason, specialist…" value="${esc(filters.search ?? "")}"></label>${select("student", "Student", unique("student"))}${select("specialist", "Specialist", unique("specialist"))}${select("room", "Room", unique("room"))}${select("reason", "Reason", unique("reason"))}<label class="filter-field"><span>SCM</span><select data-activity-filter="scm"><option value="">All</option><option value="yes" ${filters.scm === "yes" ? "selected" : ""}>Yes</option><option value="no" ${filters.scm === "no" ? "selected" : ""}>No</option></select></label></div><div class="table-toolbar log-toolbar"><div><h2>PACE visits</h2><p>${rows.length} matching record${rows.length === 1 ? "" : "s"} · Read-only</p></div></div>${rows.length ? `<div class="table-scroll"><table><thead><tr><th>Date / time</th><th>Student</th><th>Room</th><th>Reason</th><th>Support</th><th>Specialist</th><th>Duration</th><th>SCM</th></tr></thead><tbody>${[...rows].sort(sortNewest).map(visit => `<tr class="clickable-row" data-visit="${esc(visit.id)}"><td>${esc(formatDate(visit.date))}<br><span class="muted">${esc(visit.timeIn || "—")}${visit.timeOut ? `–${esc(visit.timeOut)}` : " · open"}</span></td><td><strong>${esc(visit.student || "Unnamed")}</strong></td><td>${esc(visit.room || "—")}</td><td>${esc(visit.reasons.join(", ") || "—")}</td><td>${esc(visit.interventions.join(", ") || "—")}</td><td>${esc(visit.specialists.join(", ") || "—")}</td><td>${formatMinutes(visit.durationMinutes)}</td><td>${visit.scmUsed === null ? "—" : pill(visit.scmUsed ? "Yes" : "No", visit.scmUsed ? "accent" : "neutral")}</td></tr>`).join("")}</tbody></table></div>` : emptyState("No matching visits", "Try clearing a filter or choosing a wider date range.")}</section>${activeVisit ? detailModal(activeVisit) : ""}`;
}
